---
# Doesn't use containers yet, so we need to reproduce the container.
language: bash
before_install:
- echo $PWD
# We need to install Ansible
- sudo apt-get clean all && sudo apt-get -y update
- sudo apt-get install -y python-yaml python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools git python-pip
- sudo mkdir /etc/ansible/
- echo $'[local]\nlocalhost\n' | sudo tee --append /etc/ansible/hosts
- sudo mkdir /opt/ansible/
- sudo git clone --recursive https://github.com/ansible/ansible.git /opt/ansible/ansible
- cd /opt/ansible/ansible
- sudo git submodule update --init
env:
  - PATH=/opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin:$PATH PYTHONPATH=/opt/ansible/ansible/lib:$PYTHONPATH ANSIBLE_LIBRARY=/opt/ansible/ansible/library
install:
  - ansible-playbook zenodo.yml
notifications:
  email:
    recipients:
    - brucellino@gmail.com
  slack:
    rooms:
      - africa-arabia-roc:8bySc6HbbEvvxPYqg0Z56Xdk#appdevops
