---
language: bash
before_install:
- echo $PWD
# We need to install Ansible
- yum clean all && \
  yum -y install epel-release && \
  yum -y install PyYAML python-jinja2 python-httplib2 python-keyczar python-paramiko python-setuptools git python-pip
- mkdir /etc/ansible/
- echo '[local]\nlocalhost\n' > /etc/ansible/hosts
- mkdir /opt/ansible/
- git clone --recursive https://github.com/ansible/ansible.git /opt/ansible/ansible
- cd /opt/ansible/ansible
- git submodule update --init


env:
  - PATH=/opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin:$PATH PYTHONPATH=/opt/ansible/ansible/lib:$PYTHONPATH ANSIBLE_LIBRARY=/opt/ansible/ansible/library
install:
  - ansible-playbook zenodo.yml
notifications:
  email:
    recipients:
    - brucellino@gmail.com
  slack:
    rooms:
      - africa-arabia-roc:8bySc6HbbEvvxPYqg0Z56Xdk#appdevops
